Listen 27608
Listen 27609

<VirtualHost *:27608>
    DocumentRoot /var/www/ui
    <Directory /var/www/ui>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:27609>
    DocumentRoot /var/www/api
    <Directory /var/www/api>
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
